name: Deploy Cloud Function
on:
  push:
    branches: [ main ]
env:
  GCLOUD_PROJECT_ID: investing-strategies-346514
  GCLOUD_FUNCTION_NAME: hello_world

jobs:
  build:
    runs-on: ubuntu-latest

    environment: googlecloud  # github environment in which secrets are placed

    steps:

      - uses: actions/checkout@v3

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{env.GCLOUD_PROJECT_ID}}
          service_account_key: ${{secrets.GCP_SA_JSON}}
          export_default_credentials: true

      - name: Deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ${{env.GCLOUD_FUNCTION_NAME}}
          runtime: python39
          project_id: ${{env.GCLOUD_PROJECT_ID}}
          region: europe-west1

      # - name: Aunthenticate the cloud function url 
      #   run: |
      #     gcloud functions add-iam-policy-binding ${{env.GCLOUD_FUNCTION_NAME}} --member="allUsers" --role="roles/cloudfunctions.invoker"
      # - name: Test the cloud function url
      #   run: curl "${{ steps.deploy.outputs.url }}"
